# fly.toml file generated for full-stack-phonebook-ci-cd on 2023-03-25T02:24:44+02:00

app = "full-stack-phonebook-ci-cd"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"

[deploy]
  release_command = "npm run build"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.15.0"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = 10000
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
